config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "film#mine"
  resources :home, only: [:index]
  resources :films do
    collection do
      get :mine
      get :recent
    end
    resources :comments, only: [:create, :destroy]
    resources :votes, only:[:create, :update]
  end

  resources :categories do
    member do
      get :top_films
    end
  end
end

app/models/film.rb
class Film < ApplicationRecord

  belongs_to :category
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :video, :styles => {
    :medium => { :geometry => "640x480", :format => 'flv' },
    :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
  }, :processors => [:transcoder]



  validates_attachment_presence :video
  validates_attachment_content_type :video,
    :content_type => ['video/mp4'],
    :message => "Sorry, right now we only support MP4 video",
    :if => :is_type_of_video?
  validates_attachment_content_type :video,
     :content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
     :message => "Different error message",
     :if => :is_type_of_image?
  has_attached_file :video

  def self.random_films
    self.order("RANDOM()").all
  end


  def self.last_comments
    Comment.all
  end

  def self.best_films
    Film.find_by_sql("SELECT *
        FROM films,votes
        where votes.film_id= films.id and votes.rating >= 4")

  end

  def average_rating
    rating = votes.average(:rating)
    rating ? rating.to_s : "0.0"
  end

  protected
  def is_type_of_video?
    video.content_type =~ %r(video)
  end

  def is_type_of_image?
    video.content_type =~ %r(image)
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def mine
    @films = current_user.films
    @random_films = @films.random_films
    @last_comments = Film.last_comments
    @best_films = Film.best_films
  end

  def recent
    @films = Film.all
    @random_films = Film.random_films
    @last_comments = Film.last_comments
    @best_films = Film.best_films
  end

  def new
    @film = Film.new
    load_categories
  end

  def index
    @films = Film.all
    @random_films = Film.random_films
    @last_comments = Film.last_comments
    @best_films = Film.best_films
  end

  def show
    if current_user
      if @film.votes.where(user_id: current_user.id).any?
        @vote = @film.votes.where(user_id: current_user.id).first
      else
        @vote = @film.votes.build
      end
    end
  end

  def create
    @film = current_user.films.new(film_params)
    if @film.save
        redirect_to film_path(@film)
    else
      load_categories
      render :new
    end
  end

  def edit
    load_categories
  end

  def update
  	if @film.update(film_params)
  		   redirect_to film_path(@film)
  	 else
  	      render :edit
  	 end
  end

  def destroy
    @film.destroy
    redirect_to films_path, notice: "Film was deleted"
  end

  private

    def authorize_user!
      redirect_to root_path, notice: "Not authorized" unless @film.user_id == current_user.id
    end

    def film_params
      params.require(:film).permit(:title, :description, :category_id, :image, :video)
    end

    def set_film
      @film = Film.find(params[:id])
    end

    def load_categories
      @categories = Category.all.collect { |c| [c.title, c.id] }
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film_list.html.erb
<% @random_films.each do |film| %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-plus"></i>
      <%= link_to image_tag(film.image.url(:medium)), film_path(film) %>
			<%= link_to film.category.title, category_path(film.category) %>
			<i class="fa fa-angle-right"></i>
			<%= link_to film.title, film_path(film) %>
			<span class="pull-right label label-success">{<%= film.average_rating %>}</span>
		</div>
		<div class="panel-body">
			<p>
				<%= film.description %>
			</p>
		</div>
    	<div class="panel-footer">
			<div class="pull-left">
				<p>
					<span><i class="fa fa-user"></i> <strong>Ekleyen:</strong>
					<a href="#"><%= film.user.email %></a></span>
					<span>
						<i class="fa fa-calendar-o"></i>
						<strong>Eklenme Tarihi:</strong>
						<%=
	film.user.created_at.strftime("%d %B %Y")
						%>
						</span>
		 	   	</p>
		  	</div>
	      	<div class="pull-right">
				<%= link_to film_path(film), class: "btn btn-default" do %>
					Read More
					<i class="fa fa-angle-right"></i>
				<% end %>
	      	</div>
	      	<div class="clearfix"></div>
    	</div>
	</div>
<% end %>

app/views/films/_form.html.erb
<%= form_for @film do |f| %>
<%= f.label :title %>
<%= f.text_field :title, placeholder: 'title', class: "form-control input-sm" %><br>
<br>
<%= f.label :description %>
<br>
<%= f.text_area :description, placeholder: "description", rows: 10%>
<br><br>
<div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div><br>
<div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
</div><br>
<%= f.label :category %><br>
<%= f.select :category_id, @categories %>
<br><br><br>
<%= f.submit 'Send'%>
<% end %>

app/views/films/_recent.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-lightbulb-o"></i> Random Films</div>
      <div class="list-group">
        <% @random_films.each do |film| %>

          <%= link_to film.title, film_path(film), class: "list-group-item" %>
        

        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-comments-o"></i> Last Comments</div>
      <div class="list-group">
        <% @last_comments.each do |comment| %>
        <small><%= comment.user.name %> says:</small>
               <%= comment.body %><br>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-star-o"></i> Best films</div>
      <div class="list-group">
        <% @best_films.each do |film| %>
          <%= film.title %><br>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/films/edit.html.erb
<h1>Editing <%= @film.title %></h1>

<% if @film.errors.any? %>
  <h3>
    <%= @film.errors.full_messages.join(", ") %>
  </h3>
<% end %>

<%= render partial: "form" %>

app/views/films/index.html.erb
<%= render 'film_list' %>
<%= render 'recent'%>

app/views/films/mine.html.erb
<%= render 'film_list' %>
<%= render 'recent' %>

app/views/films/new.html.erb
<h1> Create a new Film</h1>
<% if @film.errors.any? %>
  <h3>
    <%= @film.errors.full_messages.join(", ") %>
  </h3>
<% end %>
<%=render "form"%><br><br>
<%= link_to "Back to films list", films_path %><br>

app/views/films/recent.html.erb
<%= render 'recent'%>

app/views/films/show.html.erb
<%= render "flash" %>
<li class="round-image-50"><%= image_tag(@film.image.url(:thumb)) %></li><br><br>


<b> Title </b><%= @film.title %><br>
<b> Description </b><%= @film.description %><br>
<b> Category </b><%=@film.category.title %><br><br>
<b>Uploaded at: </b><%= @film.created_at %><br />
<b>User: </b><%= @film.user.name %><br /><br>
<b>Average Rating: </b><%= @film.average_rating %><br /><br>


<video autobuffer="autobuffer" preload="auto" style="width:100%;height:100%;" controls="controls" width="100%" height="100%" poster="<%= @film.video.url(:preview)%>" >
      <source  src="<%= @film.video.url%>"  />
     <%if @film.video.expiring_url(:mp4video).present? %>
     <source type="video/mp4"  src="<%= @film.video.url(:mp4video)%>" />
      <%end%>
     </video>

<%= render 'votes/form' %><br><br>
<%= render 'comments/comment_list' %><br><br>
<%= render 'comments/form' %><br><br>
<%= link_to "Back to films list", films_path %>
<% if current_user.present? and current_user.id == @film.user_id %>
  <br/>
  <%= link_to "Edit film", edit_film_path(@film) %>
  <br/>
  <%= link_to "Delete", film_path(@film), method: :delete %><br>
<% end %>