config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "film#mine"
  resources :home, only: [:index]
  resources :films do
    collection do
      get :mine
      get :recent
    end
    resources :comments, only: [:create, :destroy]
    resources :votes, only:[:create, :update]
  end

  resources :categories do
    member do
      get :top_films
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, uniqueness: true

  has_many :films

  def top_films
  films
      .joins(:votes)
      .select("films.*, avg(votes.rating) as point")
      .group("films.id")
      .order("point DESC")
      .limit(10)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy,:show,:top_films]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
        redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category deleted."
  end

  def top_films
    @films = @category.top_films
  end

  def show

  end
  
  private

  def category_params
    params.require(:category).permit(:title, :desc)
  end

  def set_category
     @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<% @categories.each do |c| %>
  <%= link_to c.title, category_path(c) %><br />
<% end %>

app/views/categories/new.html.erb
<h1> Create a new Category</h1>
<%= form_for @category do |f| %>
<%= f.label :title %>
<%= f.text_field :title, placeholder: 'title', class: "form-control input-sm" %><br>
<br>
<%= f.label :desc %>
<br>
<%= f.text_area :desc, placeholder: "description", rows: 10%>
<br>
<%= f.submit 'Send'%>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<% @category.films.each do |film| %>
  <b>ID </b><%= film.id %>
  <b>Title </b>
  <%= link_to film.title, film_path(film) %>
  <b>Description </b><%= film.description %><br>
<% end %>
<br><br><br>
<%= link_to "Top films", top_films_category_path(@category) %><br>
<%= link_to "Back to category list", categories_path %><br>
<%= link_to "Delete", category_path(@category), method: :delete %><br>

app/views/categories/top_films.html.erb
<h1>Top Films</h1>

<%= render 'films/film_list' %>