config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "film#mine"
  resources :home, only: [:index]
  resources :films do
    collection do
      get :mine
      get :recent
    end
    resources :comments, only: [:create, :destroy]
    resources :votes, only:[:create, :update]
  end

  resources :categories do
    member do
      get :top_films
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WebApp1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= recent_films_path %>">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Films", films_path %></li>
            <li><%= link_to "Categories", categories_path %></li>
            <li><%= link_to "New Film", new_film_path %></a></li>
            <li><%= link_to "New Category", new_category_path %></a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <% if current_user %>
              <h3><%=current_user.name%></h3>
            <% end %>
            <ul class="nav nav-list">
              <% if current_user %>
                <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li></br></br>
                <li><%= link_to "My Films", mine_films_path %></li>
              <% end %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
              <li><%= link_to "Register", new_user_registration_path %></li></ul><br>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Fidofilm</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>